import { mediaUrl } from '@/lib/mediaUrl';
import type { WmProduct } from '@/types/wm';
import type { TvFeatureCard, TvSectionGroup } from '@/types/tv';

const productAsset = (path: string) => mediaUrl(`/products/cac/${path}`);

const btuFromModel = (modelCode: string): string => {
  if (modelCode.includes('-18')) return '18000 BTU';
  if (modelCode.includes('-24')) return '24000 BTU';
  if (modelCode.includes('-30')) return '30000 BTU';
  if (modelCode.includes('-36')) return '36000 BTU';
  if (modelCode.includes('-48')) return '48000 BTU';
  if (modelCode.includes('-60')) return '60000 BTU';
  return '';
};

const cacGallery = [
  productAsset('cac-card.png'),
  productAsset('banner/cac-banner.jpg'),
  productAsset('1-slim-design.jpg'),
  productAsset('2-inner-high-lift-pump.jpg'),
  productAsset('3-float-switch.jpg'),
  productAsset('4-filter.jpg'),
  productAsset('5-1pa-adjustment.jpg'),
];

const cacFeatureCards: TvFeatureCard[] = [
  {
    title: 'SLIM DUCT DESIGN',
    description: 'Compact indoor unit profile for easier concealed installation',
    image: productAsset('1-slim-design.jpg'),
  },
  {
    title: 'INNER HIGH LIFT PUMP',
    description: 'Built-in pump with lift height up to 1200mm',
    image: productAsset('2-inner-high-lift-pump.jpg'),
  },
  {
    title: 'FLOAT SWITCH',
    description: 'Extra drainage protection for safer long-term operation',
    image: productAsset('3-float-switch.jpg'),
  },
  {
    title: 'WASHABLE FILTER',
    description: 'Long-life nylon filter for easier routine maintenance',
    image: productAsset('4-filter.jpg'),
  },
  {
    title: '1PA ESP ADJUSTMENT',
    description: 'Precise external static pressure control via wired controller',
    image: productAsset('5-1pa-adjustment.jpg'),
  },
];

const cacSectionGroups: TvSectionGroup[] = [
  {
    kind: 'content',
    sections: [
      { image: productAsset('1-slim-design.jpg'), copyKey: 'slimDesign' },
      { image: productAsset('2-inner-high-lift-pump.jpg'), copyKey: 'innerHighLiftPump' },
      { image: productAsset('3-float-switch.jpg'), copyKey: 'floatSwitch' },
      { image: productAsset('4-filter.jpg'), copyKey: 'filter' },
      { image: productAsset('5-1pa-adjustment.jpg'), copyKey: 'onePaAdjustment' },
    ],
  },
];

const cacBlocksEn = {
  featureIntro: {
    title: 'HID Duct Series',
    text: 'Concealed duct air conditioning with flexible ESP control, built-in drainage safety, and efficient comfort for residential and commercial spaces.',
  },
  slimDesign: {
    title: 'SLIM DESIGN',
    text: 'Designed to save ceiling space. In the slim-duct range, selected models offer a low-profile indoor unit with height as low as 190mm, helping installation in tighter ceiling voids while keeping a clean concealed look.',
  },
  innerHighLiftPump: {
    title: 'INNER HIGH LIFT PUMP',
    text: 'The built-in high lift pump can raise condensate water up to 1200mm. For smoother long-term drainage performance, the recommended drainage height is up to 800mm.',
  },
  floatSwitch: {
    title: 'FLOAT SWITCH',
    text: 'A standard float switch adds extra drainage protection. Even if the pump fails or the drain line is blocked, it helps keep water under a safe level and reduces the risk of overflow or leakage.',
  },
  filter: {
    title: 'FILTER',
    text: 'Hisense duct units come standard with a washable nylon filter. The long-life design reduces replacement frequency and allows dust to be cleaned off easily during regular maintenance.',
  },
  onePaAdjustment: {
    title: '1PA ADJUSTMENT',
    text: 'External static pressure can be adjusted through the wired controller with 1Pa precision, giving more accurate airflow setup for different duct layouts and installation conditions.',
  },
};

const cacBlocksFa = {
  featureIntro: {
    title: 'سری کانالی HID',
    text: 'کولر گازی داکت هایسنس با کنترل دقیق فشار استاتیکی، ایمنی بیشتر در تخلیه آب و عملکردی پایدار برای فضاهای مسکونی و تجاری.',
  },
  slimDesign: {
    title: 'طراحی باریک',
    text: 'طراحی‌شده برای اشغال فضای کمتر در سقف کاذب. در مدل‌های اسلیم، ارتفاع یونیت داخلی تا ۱۹۰ میلی‌متر کاهش یافته تا نصب در فضاهای محدود آسان‌تر شود و در عین حال ظاهر نهایی کاملاً یکپارچه و توکار باقی بماند.',
  },
  innerHighLiftPump: {
    title: 'پمپ درین با هد بالا',
    text: 'پمپ درین داخلی می‌تواند آب کندانس را تا ارتفاع ۱۲۰۰ میلی‌متر پمپاژ کند. برای عملکرد مطمئن و تخلیه روان در استفاده طولانی‌مدت، ارتفاع پیشنهادی لوله درین حداکثر ۸۰۰ میلی‌متر است.',
  },
  floatSwitch: {
    title: 'فلوتر سوئیچ',
    text: 'فلوتر سوئیچ به‌صورت استاندارد روی دستگاه قرار دارد و سطح آب را در محدوده ایمن نگه می‌دارد. حتی در صورت اختلال در پمپ یا گرفتگی مسیر تخلیه، این سیستم به جلوگیری از سرریز و نشت آب کمک می‌کند.',
  },
  filter: {
    title: 'فیلتر',
    text: 'یونیت‌های کانالی هایسنس به‌صورت استاندارد به فیلتر نایلونی قابل شست‌وشو مجهز هستند. این فیلتر با طول عمر بالا، نیاز به تعویض و دفعات نظافت را کاهش داده و گردوغبار به‌راحتی از روی آن پاک می‌شود.',
  },
  onePaAdjustment: {
    title: 'تنظیم فشار با دقت ۱ پاسکال',
    text: 'فشار استاتیکی خارجی از طریق کنترلر سیمی و با دقت ۱ پاسکال قابل تنظیم است؛ قابلیتی که تنظیم دقیق‌تر جریان هوا را متناسب با طول کانال و شرایط نصب ممکن می‌کند.',
  },
};

const cacCommonSpecsEn = [
  'R410A refrigerant',
  'Cooling and heating',
  'Built-in drain pump',
  'Standard float switch',
  'Washable nylon filter',
  '1Pa ESP adjustment via wired controller',
  'Electronic expansion valve (EEV)',
];

const cacCommonSpecsFa = [
  '• مبرد R410A',
  '• سرمایش و گرمایش',
  '• مجهز به پمپ درین داخلی',
  '• مجهز به فلوتر سوئیچ به‌صورت استاندارد',
  '• فیلتر نایلونی قابل شست‌وشو',
  '• تنظیم فشار استاتیکی با دقت ۱ پاسکال از طریق کنترلر سیمی',
  '• مجهز به شیر انبساط الکترونیکی (EEV)',
];

type BilingualSpecs = Record<'fa' | 'en', string[]>;

const hidSpecs: Record<string, BilingualSpecs> = {
  'hid-18s': {
    en: [
      ...cacCommonSpecsEn,
      'Cooling capacity: 5158W (1500–5800)',
      'Heating capacity: 5500W (1500–6300)',
      'Indoor power input (cooling / heating): 1535W / 1575W',
      'Indoor airflow (H/M/L): 900 / 840 / 780 m³/h',
      'EER / COP: 3.26 / 3.49',
      'ESP: 35Pa (0–50)',
      'Indoor power supply: 220–240V / 1Ph / 50Hz',
      'Indoor sound pressure (H/M/L): 41 / 37 / 33 dB(A)',
      'Indoor unit dimensions (W×H×D): 1180 × 190 × 447 mm',
      'Indoor net / gross weight: 24.5kg / 29.5kg',
      'Indoor package dimensions (W×H×D): 1350 × 565 × 285 mm',
      'Outdoor power supply: 220–240V / 1Ph / 50Hz',
      'Outdoor current input (cooling / heating): 6.67A / 6.90A',
      'Compressor: Rotary / GMCC',
      'Outdoor airflow: 2300 m³/h',
      'Outdoor sound pressure: 52 dB(A)',
      'Outdoor unit dimensions (W×H×D): 810 × 580 × 280 mm',
      'Outdoor net / gross weight: 36kg / 40kg',
      'Outdoor package dimensions (W×H×D): 940 × 420 × 640 mm',
      'Liquid / gas / drain pipe: 1/4" / 1/2" / 1 1/4"',
      'Max. piping length / height difference: 30m / 15m',
      'Refrigerant charge: 1500g',
    ],
    fa: [
      ...cacCommonSpecsFa,
      'ظرفیت سرمایش: ۵۱۵۸ وات (۱۵۰۰ تا ۵۸۰۰)',
      'ظرفیت گرمایش: ۵۵۰۰ وات (۱۵۰۰ تا ۶۳۰۰)',
      'توان ورودی یونیت داخلی (سرمایش / گرمایش): ۱۵۳۵ / ۱۵۷۵ وات',
      'حجم هوادهی یونیت داخلی (زیاد/متوسط/کم): ۹۰۰ / ۸۴۰ / ۷۸۰ مترمکعب بر ساعت',
      'EER / COP: 3.26 / 3.49',
      'فشار استاتیکی خارجی: ۳۵ پاسکال (۰ تا ۵۰)',
      'برق ورودی یونیت داخلی: ۲۲۰ تا ۲۴۰ ولت / تک‌فاز / ۵۰ هرتز',
      'سطح صدای یونیت داخلی (زیاد/متوسط/کم): ۴۱ / ۳۷ / ۳۳ دسی‌بل',
      'ابعاد یونیت داخلی (پهنا×ارتفاع×عمق): ۱۱۸۰ × ۱۹۰ × ۴۴۷ میلی‌متر',
      'وزن خالص / ناخالص یونیت داخلی: ۲۴.۵ / ۲۹.۵ کیلوگرم',
      'ابعاد بسته‌بندی یونیت داخلی (پهنا×ارتفاع×عمق): ۱۳۵۰ × ۵۶۵ × ۲۸۵ میلی‌متر',
      'برق ورودی یونیت خارجی: ۲۲۰ تا ۲۴۰ ولت / تک‌فاز / ۵۰ هرتز',
      'جریان مصرفی یونیت خارجی (سرمایش / گرمایش): ۶.۶۷ / ۶.۹۰ آمپر',
      'کمپرسور: روتاری / GMCC',
      'حجم هوادهی یونیت خارجی: ۲۳۰۰ مترمکعب بر ساعت',
      'سطح صدای یونیت خارجی: ۵۲ دسی‌بل',
      'ابعاد یونیت خارجی (پهنا×ارتفاع×عمق): ۸۱۰ × ۵۸۰ × ۲۸۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت خارجی: ۳۶ / ۴۰ کیلوگرم',
      'ابعاد بسته‌بندی یونیت خارجی (پهنا×ارتفاع×عمق): ۹۴۰ × ۴۲۰ × ۶۴۰ میلی‌متر',
      'سایز لوله مایع / گاز / درین: ۱/۴ / ۱/۲ / ۱ ۱/۴ اینچ',
      'حداکثر طول لوله‌کشی / اختلاف ارتفاع مجاز: ۳۰ / ۱۵ متر',
      'مقدار شارژ مبرد: ۱۵۰۰ گرم',
    ],
  },
  'hid-24': {
    en: [
      ...cacCommonSpecsEn,
      'Cooling capacity: 6400W (2200–7300)',
      'Heating capacity: 7250W (2500–8200)',
      'Indoor power input (cooling / heating): 1990W / 2000W',
      'Indoor airflow (H/M/L): 1100 / 950 / 850 m³/h',
      'EER / COP: 3.22 / 3.63',
      'ESP: 50Pa (0–80)',
      'Indoor power supply: 220–240V / 1Ph / 50Hz',
      'Indoor sound pressure (H/M/L): 40 / 38 / 36 dB(A)',
      'Indoor unit dimensions (W×H×D): 900 × 270 × 720 mm',
      'Indoor net / gross weight: 32kg / 37kg',
      'Indoor package dimensions (W×H×D): 1170 × 340 × 870 mm',
      'Outdoor power supply: 220–240V / 1Ph / 50Hz',
      'Outdoor current input (cooling / heating): 8.10A / 8.10A',
      'Compressor: Rotary / HITACHI',
      'Outdoor airflow: 3200 m³/h',
      'Outdoor sound pressure: 58 dB(A)',
      'Outdoor unit dimensions (W×H×D): 900 × 640 × 300 mm',
      'Outdoor net / gross weight: 50kg / 56kg',
      'Outdoor package dimensions (W×H×D): 1060 × 700 × 410 mm',
      'Liquid / gas / drain pipe: 3/8" / 5/8" / 1 1/4"',
      'Max. piping length / height difference: 30m / 15m',
      'Refrigerant charge: 1500g',
    ],
    fa: [
      ...cacCommonSpecsFa,
      'ظرفیت سرمایش: ۶۴۰۰ وات (۲۲۰۰ تا ۷۳۰۰)',
      'ظرفیت گرمایش: ۷۲۵۰ وات (۲۵۰۰ تا ۸۲۰۰)',
      'توان ورودی یونیت داخلی (سرمایش / گرمایش): ۱۹۹۰ / ۲۰۰۰ وات',
      'حجم هوادهی یونیت داخلی (زیاد/متوسط/کم): ۱۱۰۰ / ۹۵۰ / ۸۵۰ مترمکعب بر ساعت',
      'EER / COP: 3.22 / 3.63',
      'فشار استاتیکی خارجی: ۵۰ پاسکال (۰ تا ۸۰)',
      'برق ورودی یونیت داخلی: ۲۲۰ تا ۲۴۰ ولت / تک‌فاز / ۵۰ هرتز',
      'سطح صدای یونیت داخلی (زیاد/متوسط/کم): ۴۰ / ۳۸ / ۳۶ دسی‌بل',
      'ابعاد یونیت داخلی (پهنا×ارتفاع×عمق): ۹۰۰ × ۲۷۰ × ۷۲۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت داخلی: ۳۲ / ۳۷ کیلوگرم',
      'ابعاد بسته‌بندی یونیت داخلی (پهنا×ارتفاع×عمق): ۱۱۷۰ × ۳۴۰ × ۸۷۰ میلی‌متر',
      'برق ورودی یونیت خارجی: ۲۲۰ تا ۲۴۰ ولت / تک‌فاز / ۵۰ هرتز',
      'جریان مصرفی یونیت خارجی (سرمایش / گرمایش): ۸.۱۰ / ۸.۱۰ آمپر',
      'کمپرسور: روتاری / HITACHI',
      'حجم هوادهی یونیت خارجی: ۳۲۰۰ مترمکعب بر ساعت',
      'سطح صدای یونیت خارجی: ۵۸ دسی‌بل',
      'ابعاد یونیت خارجی (پهنا×ارتفاع×عمق): ۹۰۰ × ۶۴۰ × ۳۰۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت خارجی: ۵۰ / ۵۶ کیلوگرم',
      'ابعاد بسته‌بندی یونیت خارجی (پهنا×ارتفاع×عمق): ۱۰۶۰ × ۷۰۰ × ۴۱۰ میلی‌متر',
      'سایز لوله مایع / گاز / درین: ۳/۸ / ۵/۸ / ۱ ۱/۴ اینچ',
      'حداکثر طول لوله‌کشی / اختلاف ارتفاع مجاز: ۳۰ / ۱۵ متر',
      'مقدار شارژ مبرد: ۱۵۰۰ گرم',
    ],
  },
  'hid-30': {
    en: [
      ...cacCommonSpecsEn,
      'Cooling capacity: 9200W (3000–9200)',
      'Heating capacity: 9700W (3000–9900)',
      'Indoor power input (cooling / heating): 2698W / 2573W',
      'Indoor airflow (H/M/L): 1450 / 1240 / 1015 m³/h',
      'EER / COP: 3.41 / 3.77',
      'ESP: 0–120Pa',
      'Indoor power supply: 220–240V / 1Ph / 50Hz',
      'Indoor sound pressure (H/M/L): 41 / 38 / 33 dB(A)',
      'Indoor unit dimensions (W×H×D): 1140 × 268 × 720 mm',
      'Indoor net / gross weight: 37.5kg / 44.5kg',
      'Indoor package dimensions (W×H×D): 1330 × 360 × 870 mm',
      'Outdoor power supply: 220–240V / 1Ph / 50Hz',
      'Outdoor current input (cooling / heating): 11.9A / 11.0A',
      'Compressor: Rotary / GMCC',
      'Outdoor airflow: 3400 m³/h',
      'Outdoor sound pressure: 55 dB(A)',
      'Outdoor unit dimensions (W×H×D): 860 × 670 × 310 mm',
      'Outdoor net / gross weight: 47.5kg / 51.5kg',
      'Outdoor package dimensions (W×H×D): 990 × 730 × 450 mm',
      'Liquid / gas / drain pipe: 3/8" / 5/8" / 1 1/4"',
      'Max. piping length / height difference: 30m / 20m',
      'Refrigerant charge: 1650g',
    ],
    fa: [
      ...cacCommonSpecsFa,
      'ظرفیت سرمایش: ۹۲۰۰ وات (۳۰۰۰ تا ۹۲۰۰)',
      'ظرفیت گرمایش: ۹۷۰۰ وات (۳۰۰۰ تا ۹۹۰۰)',
      'توان ورودی یونیت داخلی (سرمایش / گرمایش): ۲۶۹۸ / ۲۵۷۳ وات',
      'حجم هوادهی یونیت داخلی (زیاد/متوسط/کم): ۱۴۵۰ / ۱۲۴۰ / ۱۰۱۵ مترمکعب بر ساعت',
      'EER / COP: 3.41 / 3.77',
      'فشار استاتیکی خارجی: ۰ تا ۱۲۰ پاسکال',
      'برق ورودی یونیت داخلی: ۲۲۰ تا ۲۴۰ ولت / تک‌فاز / ۵۰ هرتز',
      'سطح صدای یونیت داخلی (زیاد/متوسط/کم): ۴۱ / ۳۸ / ۳۳ دسی‌بل',
      'ابعاد یونیت داخلی (پهنا×ارتفاع×عمق): ۱۱۴۰ × ۲۶۸ × ۷۲۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت داخلی: ۳۷.۵ / ۴۴.۵ کیلوگرم',
      'ابعاد بسته‌بندی یونیت داخلی (پهنا×ارتفاع×عمق): ۱۳۳۰ × ۳۶۰ × ۸۷۰ میلی‌متر',
      'برق ورودی یونیت خارجی: ۲۲۰ تا ۲۴۰ ولت / تک‌فاز / ۵۰ هرتز',
      'جریان مصرفی یونیت خارجی (سرمایش / گرمایش): ۱۱.۹ / ۱۱.۰ آمپر',
      'کمپرسور: روتاری / GMCC',
      'حجم هوادهی یونیت خارجی: ۳۴۰۰ مترمکعب بر ساعت',
      'سطح صدای یونیت خارجی: ۵۵ دسی‌بل',
      'ابعاد یونیت خارجی (پهنا×ارتفاع×عمق): ۸۶۰ × ۶۷۰ × ۳۱۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت خارجی: ۴۷.۵ / ۵۱.۵ کیلوگرم',
      'ابعاد بسته‌بندی یونیت خارجی (پهنا×ارتفاع×عمق): ۹۹۰ × ۷۳۰ × ۴۵۰ میلی‌متر',
      'سایز لوله مایع / گاز / درین: ۳/۸ / ۵/۸ / ۱ ۱/۴ اینچ',
      'حداکثر طول لوله‌کشی / اختلاف ارتفاع مجاز: ۳۰ / ۲۰ متر',
      'مقدار شارژ مبرد: ۱۶۵۰ گرم',
    ],
  },
  'hid-36': {
    en: [
      ...cacCommonSpecsEn,
      'Cooling capacity: 10000W (2700–11800)',
      'Heating capacity: 11000W (2700–12500)',
      'Indoor power input (cooling / heating): 3250W / 2800W',
      'Indoor airflow (H/M/L): 2000 / 1700 / 1400 m³/h',
      'EER / COP: 3.08 / 3.93',
      'ESP: 47Pa (0–100)',
      'Indoor power supply: 220–240V / 1Ph / 50&60Hz',
      'Indoor sound pressure (H/M/L): 50 / 47 / 44 dB(A)',
      'Indoor unit dimensions (W×H×D): 1400 × 300 × 800 mm',
      'Indoor net / gross weight: 51kg / 57kg',
      'Indoor package dimensions (W×H×D): 1580 × 380 × 920 mm',
      'Outdoor power supply: 220–240V / 1Ph / 50Hz',
      'Outdoor current input (cooling / heating): 14.10A / 12.20A',
      'Compressor: Rotary / GMCC',
      'Outdoor airflow: 3800 m³/h',
      'Outdoor sound pressure: 57 dB(A)',
      'Outdoor unit dimensions (W×H×D): 900 × 750 × 340 mm',
      'Outdoor net / gross weight: 58kg / 61kg',
      'Outdoor package dimensions (W×H×D): 1040 × 830 × 460 mm',
      'Liquid / gas / drain pipe: 3/8" / 5/8" / 1 1/4"',
      'Max. piping length / height difference: 50m / 30m',
      'Refrigerant charge: 2400g',
    ],
    fa: [
      ...cacCommonSpecsFa,
      'ظرفیت سرمایش: ۱۰۰۰۰ وات (۲۷۰۰ تا ۱۱۸۰۰)',
      'ظرفیت گرمایش: ۱۱۰۰۰ وات (۲۷۰۰ تا ۱۲۵۰۰)',
      'توان ورودی یونیت داخلی (سرمایش / گرمایش): ۳۲۵۰ / ۲۸۰۰ وات',
      'حجم هوادهی یونیت داخلی (زیاد/متوسط/کم): ۲۰۰۰ / ۱۷۰۰ / ۱۴۰۰ مترمکعب بر ساعت',
      'EER / COP: 3.08 / 3.93',
      'فشار استاتیکی خارجی: ۴۷ پاسکال (۰ تا ۱۰۰)',
      'برق ورودی یونیت داخلی: ۲۲۰ تا ۲۴۰ ولت / تک‌فاز / ۵۰ و ۶۰ هرتز',
      'سطح صدای یونیت داخلی (زیاد/متوسط/کم): ۵۰ / ۴۷ / ۴۴ دسی‌بل',
      'ابعاد یونیت داخلی (پهنا×ارتفاع×عمق): ۱۴۰۰ × ۳۰۰ × ۸۰۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت داخلی: ۵۱ / ۵۷ کیلوگرم',
      'ابعاد بسته‌بندی یونیت داخلی (پهنا×ارتفاع×عمق): ۱۵۸۰ × ۳۸۰ × ۹۲۰ میلی‌متر',
      'برق ورودی یونیت خارجی: ۲۲۰ تا ۲۴۰ ولت / تک‌فاز / ۵۰ هرتز',
      'جریان مصرفی یونیت خارجی (سرمایش / گرمایش): ۱۴.۱۰ / ۱۲.۲۰ آمپر',
      'کمپرسور: روتاری / GMCC',
      'حجم هوادهی یونیت خارجی: ۳۸۰۰ مترمکعب بر ساعت',
      'سطح صدای یونیت خارجی: ۵۷ دسی‌بل',
      'ابعاد یونیت خارجی (پهنا×ارتفاع×عمق): ۹۰۰ × ۷۵۰ × ۳۴۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت خارجی: ۵۸ / ۶۱ کیلوگرم',
      'ابعاد بسته‌بندی یونیت خارجی (پهنا×ارتفاع×عمق): ۱۰۴۰ × ۸۳۰ × ۴۶۰ میلی‌متر',
      'سایز لوله مایع / گاز / درین: ۳/۸ / ۵/۸ / ۱ ۱/۴ اینچ',
      'حداکثر طول لوله‌کشی / اختلاف ارتفاع مجاز: ۵۰ / ۳۰ متر',
      'مقدار شارژ مبرد: ۲۴۰۰ گرم',
    ],
  },
  'hid-48s': {
    en: [
      ...cacCommonSpecsEn,
      'Cooling capacity: 13500W (4200–15000)',
      'Heating capacity: 15500W (3600–16400)',
      'Indoor power input (cooling / heating): 5400W / 5000W',
      'Indoor airflow (H/M/L): 2100 / 2000 / 1800 m³/h',
      'EER / COP: 2.50 / 3.10',
      'ESP: 60Pa (0–200)',
      'Indoor power supply: 220–240V / 1Ph / 50&60Hz',
      'Indoor sound pressure (H/M/L): 53 / 49 / 45 dB(A)',
      'Indoor unit dimensions (W×H×D): 1400 × 300 × 800 mm',
      'Indoor net / gross weight: 51kg / 57kg',
      'Indoor package dimensions (W×H×D): 1580 × 380 × 920 mm',
      'Outdoor power supply: 380–415V / 3Ph / 50&60Hz',
      'Outdoor current input (cooling / heating): 9.50A / 8.80A',
      'Compressor: Rotary / HIGHLY',
      'Outdoor airflow: 5500 m³/h',
      'Outdoor sound pressure: 58 dB(A)',
      'Outdoor unit dimensions (W×H×D): 900 × 1170 × 320 mm',
      'Outdoor net / gross weight: 83kg / 92kg',
      'Outdoor package dimensions (W×H×D): 970 × 1300 × 430 mm',
      'Liquid / gas / drain pipe: 3/8" / 3/4" / 1 1/4"',
      'Max. piping length / height difference: 50m / 30m',
      'Refrigerant charge: 3800g',
    ],
    fa: [
      ...cacCommonSpecsFa,
      'ظرفیت سرمایش: ۱۳۵۰۰ وات (۴۲۰۰ تا ۱۵۰۰۰)',
      'ظرفیت گرمایش: ۱۵۵۰۰ وات (۳۶۰۰ تا ۱۶۴۰۰)',
      'توان ورودی یونیت داخلی (سرمایش / گرمایش): ۵۴۰۰ / ۵۰۰۰ وات',
      'حجم هوادهی یونیت داخلی (زیاد/متوسط/کم): ۲۱۰۰ / ۲۰۰۰ / ۱۸۰۰ مترمکعب بر ساعت',
      'EER / COP: 2.50 / 3.10',
      'فشار استاتیکی خارجی: ۶۰ پاسکال (۰ تا ۲۰۰)',
      'برق ورودی یونیت داخلی: ۲۲۰ تا ۲۴۰ ولت / تک‌فاز / ۵۰ و ۶۰ هرتز',
      'سطح صدای یونیت داخلی (زیاد/متوسط/کم): ۵۳ / ۴۹ / ۴۵ دسی‌بل',
      'ابعاد یونیت داخلی (پهنا×ارتفاع×عمق): ۱۴۰۰ × ۳۰۰ × ۸۰۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت داخلی: ۵۱ / ۵۷ کیلوگرم',
      'ابعاد بسته‌بندی یونیت داخلی (پهنا×ارتفاع×عمق): ۱۵۸۰ × ۳۸۰ × ۹۲۰ میلی‌متر',
      'برق ورودی یونیت خارجی: ۳۸۰ تا ۴۱۵ ولت / سه‌فاز / ۵۰ و ۶۰ هرتز',
      'جریان مصرفی یونیت خارجی (سرمایش / گرمایش): ۹.۵۰ / ۸.۸۰ آمپر',
      'کمپرسور: روتاری / HIGHLY',
      'حجم هوادهی یونیت خارجی: ۵۵۰۰ مترمکعب بر ساعت',
      'سطح صدای یونیت خارجی: ۵۸ دسی‌بل',
      'ابعاد یونیت خارجی (پهنا×ارتفاع×عمق): ۹۰۰ × ۱۱۷۰ × ۳۲۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت خارجی: ۸۳ / ۹۲ کیلوگرم',
      'ابعاد بسته‌بندی یونیت خارجی (پهنا×ارتفاع×عمق): ۹۷۰ × ۱۳۰۰ × ۴۳۰ میلی‌متر',
      'سایز لوله مایع / گاز / درین: ۳/۸ / ۳/۴ / ۱ ۱/۴ اینچ',
      'حداکثر طول لوله‌کشی / اختلاف ارتفاع مجاز: ۵۰ / ۳۰ متر',
      'مقدار شارژ مبرد: ۳۸۰۰ گرم',
    ],
  },
  'hid-60s': {
    en: [
      ...cacCommonSpecsEn,
      'Cooling capacity: 15500W (4800–16200)',
      'Heating capacity: 15500W (4000–17500)',
      'Indoor power input (cooling / heating): 6330W / 4850W',
      'Indoor airflow (H/M/L): 2400 / 2300 / 2200 m³/h',
      'EER / COP: 2.45 / 3.20',
      'ESP: 60Pa (0–200)',
      'Indoor power supply: 220–240V / 1N / 50&60Hz',
      'Indoor sound pressure (H/M/L): 52 / 49 / 46 dB(A)',
      'Indoor unit dimensions (W×H×D): 1400 × 300 × 800 mm',
      'Indoor net / gross weight: 51kg / 57kg',
      'Indoor package dimensions (W×H×D): 1580 × 380 × 920 mm',
      'Outdoor power supply: 380–415V / 3N / 50&60Hz',
      'Outdoor current input (cooling / heating): 10.67A / 8.17A',
      'Compressor: Rotary / HIGHLY',
      'Outdoor airflow: 5500 m³/h',
      'Outdoor sound pressure: 59 dB(A)',
      'Outdoor unit dimensions (W×H×D): 900 × 1170 × 320 mm',
      'Outdoor net / gross weight: 86.5kg / 95kg',
      'Outdoor package dimensions (W×H×D): 970 × 1300 × 430 mm',
      'Liquid / gas / drain pipe: 3/8" / 3/4" / 1 1/4"',
      'Max. piping length / height difference: 50m / 30m',
      'Refrigerant charge: 4000g',
    ],
    fa: [
      ...cacCommonSpecsFa,
      'ظرفیت سرمایش: ۱۵۵۰۰ وات (۴۸۰۰ تا ۱۶۲۰۰)',
      'ظرفیت گرمایش: ۱۵۵۰۰ وات (۴۰۰۰ تا ۱۷۵۰۰)',
      'توان ورودی یونیت داخلی (سرمایش / گرمایش): ۶۳۳۰ / ۴۸۵۰ وات',
      'حجم هوادهی یونیت داخلی (زیاد/متوسط/کم): ۲۴۰۰ / ۲۳۰۰ / ۲۲۰۰ مترمکعب بر ساعت',
      'EER / COP: 2.45 / 3.20',
      'فشار استاتیکی خارجی: ۶۰ پاسکال (۰ تا ۲۰۰)',
      'برق ورودی یونیت داخلی: ۲۲۰ تا ۲۴۰ ولت / 1N / ۵۰ و ۶۰ هرتز',
      'سطح صدای یونیت داخلی (زیاد/متوسط/کم): ۵۲ / ۴۹ / ۴۶ دسی‌بل',
      'ابعاد یونیت داخلی (پهنا×ارتفاع×عمق): ۱۴۰۰ × ۳۰۰ × ۸۰۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت داخلی: ۵۱ / ۵۷ کیلوگرم',
      'ابعاد بسته‌بندی یونیت داخلی (پهنا×ارتفاع×عمق): ۱۵۸۰ × ۳۸۰ × ۹۲۰ میلی‌متر',
      'برق ورودی یونیت خارجی: ۳۸۰ تا ۴۱۵ ولت / 3N / ۵۰ و ۶۰ هرتز',
      'جریان مصرفی یونیت خارجی (سرمایش / گرمایش): ۱۰.۶۷ / ۸.۱۷ آمپر',
      'کمپرسور: روتاری / HIGHLY',
      'حجم هوادهی یونیت خارجی: ۵۵۰۰ مترمکعب بر ساعت',
      'سطح صدای یونیت خارجی: ۵۹ دسی‌بل',
      'ابعاد یونیت خارجی (پهنا×ارتفاع×عمق): ۹۰۰ × ۱۱۷۰ × ۳۲۰ میلی‌متر',
      'وزن خالص / ناخالص یونیت خارجی: ۸۶.۵ / ۹۵ کیلوگرم',
      'ابعاد بسته‌بندی یونیت خارجی (پهنا×ارتفاع×عمق): ۹۷۰ × ۱۳۰۰ × ۴۳۰ میلی‌متر',
      'سایز لوله مایع / گاز / درین: ۳/۸ / ۳/۴ / ۱ ۱/۴ اینچ',
      'حداکثر طول لوله‌کشی / اختلاف ارتفاع مجاز: ۵۰ / ۳۰ متر',
      'مقدار شارژ مبرد: ۴۰۰۰ گرم',
    ],
  },
};

const buildCacProduct = (id: string): WmProduct => {
  const model = id.toUpperCase();
  const btu = btuFromModel(model);

  return {
    id,
    sku: model,
    series: 'HID',
    seriesLabel: 'HID Duct Series',
    sizes: btu ? [btu] : [],
    extras: [
      'Cooling and heating',
      'Built-in drain pump',
      'Float switch',
      'Washable nylon filter',
      '1Pa ESP adjustment',
      'EEV',
    ],
    image: productAsset('cac-card.png'),
    posterImage: productAsset('cac-card.png'),
    gallery: cacGallery,
    featureCards: cacFeatureCards,
    sectionGroups: cacSectionGroups,
    specs: hidSpecs[id],
    copy: {
      en: {
        name: `Hisense Duct Air Conditioner ${model}`,
        tagline: 'HID Duct Series | Cooling and heating',
        description:
          'Hisense HID duct air conditioner combines concealed installation, precise ESP control, built-in drainage safety, and reliable cooling and heating performance for residential and commercial projects.',
        highlights: [
          'Cooling and heating',
          'Built-in high lift drain pump',
          'Standard float switch',
          'Washable nylon filter',
          '1Pa ESP adjustment',
        ],
        blocks: cacBlocksEn,
      },
      fa: {
        name: `کولر گازی داکت هایسنس ${model}`,
        tagline: 'سری کانالی HID | سرمایش و گرمایش',
        description:
          'کولر گازی داکت هایسنس سری HID با نصب توکار، کنترل دقیق فشار استاتیکی، ایمنی بیشتر در تخلیه آب و عملکرد مطمئن سرمایش و گرمایش، انتخابی کارآمد برای پروژه‌های مسکونی و تجاری است.',
        highlights: [
          'سرمایش و گرمایش',
          'پمپ درین داخلی با هد بالا',
          'فلوتر سوئیچ استاندارد',
          'فیلتر نایلونی قابل شست‌وشو',
          'تنظیم فشار با دقت ۱ پاسکال',
        ],
        blocks: cacBlocksFa,
      },
    },
  };
};

const hidModels = ['hid-18s', 'hid-24', 'hid-30', 'hid-36', 'hid-48s', 'hid-60s'];

export const CAC_PRODUCTS: WmProduct[] = hidModels.map(buildCacProduct);
