// AUTO-GENERATED by scripts/detect-mono-logos.ts — do not edit by hand.
// Black-on-transparent feature-card logos that are inverted to white on the
// dark feature-card tile. Re-run `npm run logos:scan` after changing logo assets.

export const MONO_FEATURE_LOGOS = new Set<string>([
  'refrigerator/logos/fs-270/1-total-no-frost-icon.png',
  'refrigerator/logos/fs-270/2-super-freeze-icon.png',
  'refrigerator/logos/fs-270/5-premium-appearance-icon.png',
  'refrigerator/logos/fs-270/7-low-noise-icon.png',
  'refrigerator/logos/rft-560/1-sleek-water-dispenser-icon.png',
  'refrigerator/logos/rft-560/2-durable-inverter-icon.png',
  'refrigerator/logos/rft-560/3-total-no-frost-icon.png',
  'refrigerator/logos/rft-560/4-super-cool.png',
  'refrigerator/logos/rft-560/5-multiair-flow.png',
  'refrigerator/logos/rft-560/6-electronic-touch-control.png',
  'refrigerator/logos/rft-560/7-soft-led-lighting.png',
  'refrigerator/logos/rft-560/8-super-freeze.png',
  'refrigerator/logos/rs-370/1-easy-open-door-handle-icon.png',
  'refrigerator/logos/rs-370/2-fresh-crisper-icon.png',
  'refrigerator/logos/rs-370/3-full-width-airflow-icon.png',
  'refrigerator/logos/rs-370/8-super-cool-icon.png',
  'tvs/logos/Dolby-Vision-Atoms-svg-dark.png',
  'tvs/logos/colour-enhancer-logo.png',
  'tvs/logos/depth-enhancer-logo.png',
  'tvs/logos/noise-reduction-logo.png',
  'whashing-machine/logos/alregy-steam.png',
  'whashing-machine/logos/durable-inverter.png',
  'whashing-machine/logos/lint-clean.png',
  'whashing-machine/logos/quick-wash-dry.png',
  'whashing-machine/logos/quick-wash.png',
  'whashing-machine/logos/selt-diagnostics.png',
]);
