// Renders a feature-card logo on the dark feature-card tile.
// The tile is dark in both themes, so we always use the light/white variant
// (imageBlack) when a logo ships a light+dark pair, and invert the pure-black
// line icons to white (set generated by `npm run logos:scan`).
import Image from 'next/image';
import type { ImageSource } from '@/types/tv';
import { MONO_FEATURE_LOGOS } from '@/content/monoFeatureLogos.generated';

type FeatureCardImageProps = {
  title: string;
  image: ImageSource;
  imageBlack?: ImageSource;
  className: string;
};

// Derive the manifest key ("tvs/logos/foo.png") from a resolved src in either
// local ("/products/...") or CDN ("https://cdn/products/...") form.
function monoKey(src: string): string {
  const clean = src.split('?')[0];
  const marker = '/products/';
  const idx = clean.indexOf(marker);
  return idx === -1 ? clean : clean.slice(idx + marker.length);
}

export default function FeatureCardImage({
  title,
  image,
  imageBlack,
  className,
}: FeatureCardImageProps) {
  // Use `||` not `??`: the API normalizes a missing dark variant to "" (empty
  // string), which is not nullish — `??` would keep it and pass "" to <Image>.
  // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
  const src = imageBlack || image;
  const resolved = typeof src === 'string' ? src : src.src;
  const isSvg = resolved.split('?')[0].toLowerCase().endsWith('.svg');
  const isMono = MONO_FEATURE_LOGOS.has(monoKey(resolved));

  return (
    <Image
      src={src}
      alt={title}
      width={320}
      height={320}
      className={`${className}${isMono ? ' brightness-0 invert' : ''}`}
      unoptimized={isSvg}
    />
  );
}
